"""Generate data/DATACARD.md from data/manifest.json and data/LICENSES.md so the
data card's numbers cannot drift from what was actually sharded.

Usage: python datacard.py [--profile main3b_ext_lit15rep05xqa50_tng03]
"""
import argparse, json, os, re, time

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--profile", default=None, help="manifest profile key (default: the most recent main3b* profile)")
    a = ap.parse_args()
    m = json.load(open("data/manifest.json"))
    ent = m.get("releasing_entity", {})
    profiles = [k for k in m if k.startswith("main3b")] or [k for k in m if k != "releasing_entity"]
    prof = a.profile or profiles[-1]   # manifest keys are the shard directory names (e.g. main3b_ext_<mix>)
    src = m[prof]["sources"]
    total = sum(v["tokens"] for v in src.values())
    lines = [f"# Data card: {', '.join(ent.get('models', []))}", "",
             f"Releasing entity: {ent.get('name')} ({ent.get('location')}), Hugging Face organisation \"{ent.get('hf_org')}\".",
             ent.get("note", ""), "",
             f"Generated by datacard.py from data/manifest.json (profile `{prof}`) on {time.strftime('%F')}; license rows come from data/LICENSES.md.", "",
             "| bucket | source_id | documents | tokens | share |", "|---|---|---|---|---|"]
    for sid, v in sorted(src.items(), key=lambda kv: -kv[1]["tokens"]):
        lines.append(f"| {v['bucket']} | {sid} | {v['docs']:,} | {v['tokens']/1e6:,.1f}M | {v['tokens']/total:.3%} |")
    lines += ["", f"Total: {total/1e9:.2f}B training tokens (extended tokenizer). Repetition: literature tier 1 capped at 16 passes, tier 2 at 8; other buckets as sharded.", "",
              "## Licenses (from data/LICENSES.md)", ""]
    lic = open("data/LICENSES.md").read()
    lines.append(lic)
    lines += ["", "## Knowledge cutoff",
              "Tamil Wikipedia content is from the 2023-11 dump (to be updated to 2026-08 only if the recency top-up experiment is kept); web crawl cutoff 2025-10 (fineweb-2 release); IndicCorpV2 is a 2022-2023 crawl. The model has no knowledge of events after that, and as a 2B model it makes factual errors outside the literature knowledge base."]
    lines += ["", "## Wikipedia-derived instruction rows (round 3 onwards)",
              "Some supervised fine-tuning rows are grounded on Tamil Wikipedia and Tamil Wikibooks passages (CC BY-SA 4.0). Each such row carries the source title and URL; served answers that draw on Wikipedia carry an attribution line; these rows are Wikipedia-derived under CC BY-SA and are never redistributed under any other license."]
    lines += ["", "## What is and is not redistributed",
              "Published: model weights, code, eval sets and splits, this data card, augmentation scripts, and the structured literature KB for public-domain or open-licensed sources. Not published: raw crawled corpora (used for training under the upstream terms, contain copyrighted material), Project Madurai files, and synthetic renderings derived from non-redistributable sources."]
    os.makedirs("data", exist_ok=True)
    open("data/DATACARD.md", "w").write("\n".join(lines))
    print(f"wrote data/DATACARD.md: {len(src)} sources, {total/1e9:.2f}B tokens, profile {prof}")

if __name__ == "__main__":
    main()
